stages:
  data_collection:
    cmd: python src/data_collection.py
    deps:
    - src/data_collection.py
    outs:
    - data/raw


  pre_processing:
    cmd: python src/data_preprocessing.py --force
    deps:
    - data/raw
    - src/data_preprocessing.py
    outs:
    - data/preprocessed
  model_building:
    cmd: python src/model_building.py --force
    deps:
    - data/preprocessed
    - src/model_building.py
    outs:
    - model.pkl
  model_eval:
    cmd: python src/model_eval.py
    deps:
    - model.pkl
    - src/model_eval.py
    metrics:
    - metrics.json
